import { doc, getDoc, setDoc } from "firebase/firestore"

import { db } from "../firebase"

export const createUser = async (uid, displayName) => {
  const generateUserUnique = Math.floor(Math.random() * 1000000).toString()

  //check first if there already is a user with that id:
  const docRef = doc(db, "users", uid)

  try {
    const docSnap = await getDoc(docRef)

    if (docSnap.exists()) {
      return
    } else {
      try {
        const newDoc = await setDoc(doc(db, "users", uid), {
          displayName,
          usersUnique: generateUserUnique,
          friends: [],
          friendRequests: [],
          sentRequests: [],
        })
      } catch (error) {
        console.log(error)
      }

      try {
        const userUnique = await setDoc(
          doc(db, "usersUniques", generateUserUnique),
          {
            uid: uid,
          }
        )
      } catch (error) {
        console.log(error)
      }
    }
  } catch (error) {
    console.log(error)
  }
}

/* 

users schema model:

users: documents of users ids ->
document: usersUnique: "123456" //string of length 6 number
          friends: [
            {
              uid: "gbw45Hre", // the standard uid generated by google
              displayName: "sebastianSemeniuc",
              photoUrl: "...photoUrl", // photoUrl from google
            }, 

            {
              uid: "gbw45Hre", // the standard uid generated by google
              displayName: "sebastianSemeniuc",
              photoUrl: "...photoUrl", // photoUrl from google
            }
          ],

          friendRequests: [
            {
              uid: "creG34rv3rvdce",
              displayName: "sebastianSemeniuc",
              photoUrl: "linkToDisplayPhoto"
          }
          ]

*/
